- id: gdshaderlint
  name: gdshaderlint
  description: "gdshaderlint - linter for GDShader"
  entry: gdshaderlint
  language: python
  language_version: python3
  require_serial: true
  types: [gdshader]
- id: gdshaderformat
  name: gdshaderformat
  description: "gdshaderformat - formatter for GDShader"
  entry: gdshaderformat
  language: python
  language_version: python3
  require_serial: true
  types: [gdshader]
