name: godot-gdshader-toolkit
description: GitHub Action to install Godot GDShader Toolkit
author: Gray Espinoza

branding:
  icon: align-left
  color: black

inputs:
  version:
    description: version of Godot GDShader Toolkit to install
