name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main
    paths-ignore:
      - "**/*.md"

jobs:
  tox:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Set Up Python ${{ matrix.python-version }} On ${{ matrix.os }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install Dependencies
        run: python -m pip install --upgrade pip setuptools tox
      - name: Run tox
        run: tox
  analyze:
    runs-on: [ubuntu-latest]
    permissions:
      security-events: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
